sudo: required

#language: python
dist: trusty

services:
  - docker

before_install:
- docker build -t xyce-parallel-test -f Dockerfile-test.parallel .

script:
#- docker ps | grep -q 
- docker run xyce-parallel-test sh -c "./xyce-build/xyce-tests.sh" 

