sudo: required

#language: python
dist: trusty

services:
  - docker

before_install:
- docker build -t xyce-parallel-test -f Dockerfile-test.parallel .

script:
#- docker ps | grep -q 
- docker run -v /Xyce_Test:/opt/Xyce/Xyce_Test xyce-parallel-test sh -c "cd ./xyce-build/; ./xyce-tests.sh; exit 0"
- $(if grep -i '\.failed' /Xyce_Test/test_results 1>&2; then exit -1; else exit 0; fi)
 


