sudo: required

#language: python
dist: trusty

services:
  - docker

before_install:
- docker build -t xyce-parallel-test -f Dockerfile.parallel.test .

script:
#- docker ps | grep -q 
- docker run xyce-parallel-test ./xyce-test.sh 

